dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<2.3"
matrix:  # see https://docs.djangoproject.com/en/dev/faq/install/
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "2.7"
      env: DJANGO="Django>=2.2,<2.3"
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO="Django>=2.2,<2.3"
# command to install dependencies
install:
  - pip install $DJANGO
  - pip install coveralls
  - python setup.py develop
script: coverage run example/manage.py test -v2
after_success:
  - coveralls
